name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      ARROW_TEST_DATA: /__w/simply-query-engine/simply-query-engine/testing/data
      PARQUET_TEST_DATA: /__w/simply-query-engine/simply-query-engine/parquet-testing/data
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: Swatinem/rust-cache@v1

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
